# Generated by Django 5.2 on 2025-05-01 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(max_length=100)),
                ('usage_time_hours', models.FloatField()),
                ('electricity_needed_kwh', models.FloatField()),
                ('electricity_wasted_kwh', models.FloatField()),
                ('cost_per_kwh', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_usages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
